### ISSUE TITLE
Ubuntu version not working

### ISSUE THREAD

**Issue by andreped** [AICAN-Research/FAST-Pathology#22]
Tried downloading the latest artifact on Ubuntu 18.04. Not working.

Did `sudo dpkg -i fastpathology_ubuntu18.04_1.0.0.deb` and run it. Nothing happened. Checked `/opt/fastpathology/`, it is there. Tried running the program from the bin/ directory, and this prompted:
```
INFO [139839184267968] Found variable filename in pipeline file
ERROR [139839184267968] Terminated with unhandled exception: The pipeline file requires you to give a value for the variable named filename
This is done by adding --filename <value> to the command line arguments
Aborted (core dumped)
```

Old release works just fine.

**Comment by andreped** [comment]
Hmm, now I got the same issue on Windows. But this happened after uninstalling and reinstalling.

Might be that something is not properly deleted. The program crashes immediantly at launch.

**Comment by andreped** [comment]
Also, data/ directory is not removed after uninstalling - observed for windows.

**Comment by andreped** [comment]
After manually deleting files in `C:\Users\andrp\fastpathology`, the program launched and I was asked to download the models. So I believe the uninstall method has a bug - not everything is properly deleted.

**Comment by smistad** [comment]
This was due to your old pipelines not being supported by the new software. I added a try-catch to capture this kinds of errors, to just ignore pipelines that are incorrect.
