### ISSUE TITLE
Magnification selection not working properly

### ISSUE THREAD

**Issue by andreped** [AICAN-Research/FAST-Pathology#24]
Tried to run the BACH model on a x40 WSI, and it crashed due to:
```
Exception caught: Thread stopped because: No level close enough to magnification of 20 was found in the image pyramid.
```

This image plane exists, so there is something wrong.

**Comment by andreped** [comment]
Same for the breast cancer segmentation pipeline:
```
Exception caught: Thread stopped because: No level close enough to magnification of 10 was found in the image pyramid.
```

**Comment by andreped** [comment]
Just tested on a WSI stored in the CellSens VSI format and this works, but it fails for the TIFF format.

Perhaps it only works for the CellSens VSI format currently?

WSIs are stored on the sintef server for testing, in the images/ directory where all the other pathology stuff lies.

**Comment by smistad** [comment]
This was a bug in FAST, conversion of spacing from TIFF was incorrect. Fixed in: https://github.com/smistad/FAST/commit/9d11f1675fecca64335a1b302e63790bfea16103
