### ISSUE TITLE
Some issues with display of rendering, etc.

### ISSUE THREAD

**Issue by SahPet** [AICAN-Research/FAST-Pathology#36]
I have briefly tested the new FastPathology version. More stable. but some issues:

1. crashes when I try to load small tiff files, but not large ones. When I test prediction for mitoses they become invisible at "overview" ca. 4x magnification and thus it becomes almost pointless to run the algorithm when you have to look for all green dots. In Qupath, small annotations are magnified when you zoom out so they are still visible. Is this possible to get into FastPathology (that all annotations have a given line thickness regardless of magnification?) 

2. The NoCodeSeg import script does not work on the tiff file I got out in the results folder. Correct size, but too large for the import script (this was a standard WSI, but large about 60k x 100k pixels, and MIB/DeepMIB/Matlab struggles with these as well at 40x resolution). 

3. The import script for direct import from fast pathology at the NoCodeSeg page probably does not work either as it is a new folder structure with lots of subfolders. I would have dropped all these subfolders in results, or at least had a little less of them.

5. It is difficult to know whether the algorithm is actually running or not - no progress bar and no time indication for estimated finished prediction. For mitoses, I waited 15 minutes and it was finished, but could just as easily have been nothing that happened - I did not know that as a user.

**Comment by andreped** [comment]
Great suggestions, @SahPet!

Some of these suggestions, there already exists issues for. For 1) see https://github.com/AICAN-Research/FAST-Pathology/issues/33, and 2) see https://github.com/AICAN-Research/FAST-Pathology/issues/35, which I just created an issue for after discussing this with you on Teams.

Next time it is better to split sets of issues into individual issues on github.

That makes it easier for us to track, and we can more easily distribute the workload.

But great suggestions, we will try to solve all of them within a reasonable amount of time :)

**Comment by SahPet** [comment]
So, here is a visual demo of what the point:

Segmentation networks for small rare objects, such as mitoses, rare cell types, etc. are not visible on the overview, which makes its really hard to use FastPathology for this purpose:
![Screenshot_291](https://user-images.githubusercontent.com/43611111/189355444-1c243c78-4807-4c0e-8ba5-e43dd8601473.jpg)

.... even though there are quite a few there:
![Screenshot_292](https://user-images.githubusercontent.com/43611111/189355652-e98e979e-cd4d-4d04-9eae-6cab2a8f9bfe.jpg)

In QuPath for example, small objects are clearly visible at full overview as well as on full zoom, so should be possible, by keeping the border line thickness rendering independent on zoom level for example.

**Comment by andreped** [comment]
Some of the points here has been adressed already. Whereas for those that remains, new targeted Issues have been created. Hence, this is now a duplicate. Closing this issue for now.
