### ISSUE TITLE
Rendering offset for some WSI formats

### ISSUE THREAD

**Issue by andreped** [AICAN-Research/FAST-Pathology#38]
Just run the nuclei segmentation pipeline which follows with FP on a local WSI, and observed that the rendered segmentations were off.

This was observed for a WSI stored in the generic TIFF format, on Windows 10, using the latest artifact.

See example below.

![offset_test_fp](https://user-images.githubusercontent.com/29090665/173349264-cfe79cf4-9c30-4d09-b3cc-546e3df26059.png)

**Comment by andreped** [comment]
Just observed the same using the latest artefact when testing a custom mitosis segmentation model.

I was running a lot of different tests. I could not reproduce this issue on the CellSens VSIs, but for the generic TIFF images, it seems to reproduce quite consistently.

![Skjermbilde 2022-10-23 210536](https://user-images.githubusercontent.com/29090665/197410853-b70e470f-d97e-41da-9286-b96560a244fe.png)

However, I find it strange, as these images were originally stored as .vsi, but converted to .tiff. I believe this used to work before. Not sure what changed. Might also be that the converter stores some spacing data wrong.

There should be some WSIs located on the SINTEF-server you could test:
/mnt/EncryptedPathology/pathology/images_tiff_tz_1024_jpeg_85/T.tif

I observed the same issue using the nuclei segmentation method that is part of the software. If that WSI is not in the path, you could test any of the .tif-files. I believe it should be consistent among those files, but not sure.

**Comment by smistad** [comment]
This is caused by pixel spacing of segmentation being calculating incorrectly. 

We are not able to extract spacing information from the VSI format, that is why it is not occurring on these images.

**Comment by andreped** [comment]
> We are not able to extract spacing information from the VSI format

I'm observing this issue on the TIFF images, not the VSI images. But the TIFF images were originally in the VSI format. The TIFF images are located at:
/mnt/EncryptedPathology/pathology/images_tiff_tz_1024_jpeg_85/

The corresponding VSI images are located at:
/mnt/EncryptedPathology/pathology/images/

on the SINTEF server, if I recall correctly, if you wish to check this further.

**Comment by vladpopovici** [comment]
Hello,

I have observed the same behavior on .MRXS whole slide images, on Windows, with latest release (v1.1.0), with all segmentation models. I can provide a test image if needed.
Thanks,
Vlad

**Comment by andreped** [comment]
That's interesting, @vladpopovici! Thanks for reporting it!

@smistad is on vacation now and I am preoccupied with some other deadlines, so we will not be able to look into this until August earliest. Will keep you updated!

Regarding test data, could you reproduce the issue on any of the MXRS files that are part of the OpenSlide test data (see [here](https://openslide.cs.cmu.edu/download/openslide-testdata/Mirax/)).

**Comment by vladpopovici** [comment]
Now that's awkward: on the test data the segmentation mask is spot on! I will take a closer look to see what are the differences in metadata between test images and mine. My images are produced by the scanner software for 3DHistech. Keep you posted. V.

**Comment by andreped** [comment]
> My images are produced by the scanner software for 3DHistech.

Oh, yeah. This we have seen in a separate issue. See issue #13 (or more specifically, see [this comment](https://github.com/AICAN-Research/FAST-Pathology/issues/13#issuecomment-1017505495)). Basically, the MRXS format produced from the 3DHistech format has been _modified_, which results in OpenSlide failing to interpret it correctly. This was also talked about thoroughly [in this thread](https://forum.image.sc/t/mrxs-files-in-qupath/37070/2?u=andreped).

To get these images to work with non 3DHistech-products, you will need to use the 3D Histech converter tool (see [here](https://github.com/AICAN-Research/FAST-Pathology/issues/13#issuecomment-1149985054)). Which should resolve this issue, but I have myself never tried it. Could you give it a go to see if it resolves the issue you are experiencing on your local WSI?

**Comment by vladpopovici** [comment]
I can confirm the observations made by @pr4deepr:

-original .MRXS from 3DHistech scanner is read by FP, but segmentation is shifted;
-.MRXS -> .TIFF converted by 3DHistech software (SlideMaster) results in a file that cannot be read in FP;
-.MRXS -> .MRXS results in a file that can be read in FP, but the segmentation is shifted;

Additionally, I tried .MRXS -> OME-TIFF (with bioformats tools: [bioformats2raw](https://github.com/glencoesoftware/bioformats2raw) + [raw2ometiff](https://github.com/glencoesoftware/raw2ometiff) which results in a file that cannot be read by FP ("level is too large to convert into a FAST image").

**Comment by andreped** [comment]
The annoying problem is basically that the 3DHistech have corrupted the original MRXS format slightly, meaning that for FP the regular OpenSlide test MRXS files reads as expected, but the one directly for the 3DHistech server does not.

> -.MRXS -> .TIFF converted by 3DHistech software (SlideMaster) results in a file that cannot be read in FP;

I believe that is because it does not produce a pyramidal TIFF, which is needed to be read by FP. If you try to open it in QuPath, it will likely open, it might take a while and prompt a warning, as it will try to pyramidize the entire image before reading it.

> Additionally, I tried .MRXS -> OME-TIFF (with bioformats tools: [bioformats2raw](https://github.com/glencoesoftware/bioformats2raw) + [raw2ometiff](https://github.com/glencoesoftware/raw2ometiff) which results in a file that cannot be read by FP ("level is too large to convert into a FAST image").

That is related to the previous comment. I would recommend using `bioformats` + `vips` instead. That is you first convert the WSI to BigTIFF and then to a pyramidal TIFF. See [this example python script](https://github.com/andreped/vsi2tif/blob/fd7cfafe82b24a989e9f1b79e324ae60f7e84a9b/vsi2tif.py#L50) on how to do it. Note that I just use two command line tools. Below is a simple example of how to do it:

```
# original format -> btf
> sh /path/to/bfconvert -tilex 1024 -tiley 1024 -nogroup -no-upgrade -overwrite -bigtiff -series 0 /path/to/original/image.format /path/to/temporary/image.btf

# btf -> pyramidal tif
> vips tiffsave /path/to/temporary/image.btf /path/to/converted/image.tif --bigtiff --tile -pyramid --compression=jpeg --Q=85
```

See the aforementioned script for more information regarding compression in the first step and bfconvert path.

**Comment by vladpopovici** [comment]
The bfconvert produces a corrupted image that vips fails to convert afterwards.
But I have used this command, which should be (?) equivalent:

`> vips openslideload <file>.mrxs <result_file>.tiff[tile,tile-width=1024,tile-height=1024,compression=jpeg,Q=100,bigtiff,pyramid] --vips-progress`

The resulting file is perfectly opened by FP, but the detection mask is, again, shifted. I will have to check in the code to see which meta-parameters are causing this behavior. It's really frustrating... :)

**Comment by andreped** [comment]
I believe by attempting to convert in another software than 3DHistech's own converter, you will likely still get the offset.

Did you try to use the converter I mentioned previously. Might be that it has been rebranded to [slidemaster](https://www.3dhistech.com/research/slidecenter/slidemaster/).

**Comment by vladpopovici** [comment]
Yes, I tried with SlideMaster - see my attempts above.
Anyhow, I did not see this kind of artifact in other programs analyzing the same images (including QuPath, HALO and my own scripts :) ). I used OpenSlide previously and I was able to correctly align the masks and navigate the images. 
I will try digging into the code of FAST library.

**Comment by andreped** [comment]
I guess this is something that could be addressed in FAST then. We have a similar issue with some other WSI formats, so it should be possible to resolve. However, @smistad is on vacation, so it will have to wait until August.

**Comment by cavenel** [comment]
Hi,

As discussed on https://forum.image.sc/t/nocodeseg-deep-learning-based-segmentation-without-code-qupath-deepmib-fastpathology/60069/10, I have the exact same shifting problem in FAST (via FastPathology).
The WSI file is from 3DHistech, and I attach the openslide properties here: [openslide_output.txt](https://github.com/AICAN-Research/FAST-Pathology/files/12300682/openslide_output.txt)

And the shift looks like this:
![image](https://github.com/AICAN-Research/FAST-Pathology/assets/6164758/001d9f99-090a-4339-bdae-24af52f9ece6)

I can send a test image if needed.
This is a bit blocking for me, as no conversion worked: vips keeps the shift issue, and QuPath makes an OME.TIFF that FAST can not open.

**Comment by andreped** [comment]
> I can send a test image if needed.

Hello, @cavenel! It would be great if you could share an image, such that we could see if we could reproduce the issue. It would also help us in debugging the issue and potentially finding a fix.

If you do not wish to make it open to everyone, you could share the WSI with me at: andrped94@gmail.com

**Comment by andreped** [comment]
Note that we have resolved similar issues before for a difference image format: https://github.com/AICAN-Research/FAST-Pathology/issues/61#issuecomment-1451966053

Also note that for this exact format, @pr4deep seemed to have managed to resolve this issue for the same 3DHistech MRXS format by converting the format to TIFF using 3DHistech's own converter: https://github.com/AICAN-Research/FAST-Pathology/issues/13#issuecomment-1165029997

@cavenel Could you please check again that you did the conversion correctly. This is also relevant for @vladpopovici (see comment below).

> -.MRXS -> .TIFF converted by 3DHistech software (SlideMaster) results in a file that cannot be read in FP;

@vladpopovici I believe the conversion you did here actually fixed it, but you have to convert the image to pyramidal TIFF, not regular TIFF, as FastPathology only works with pyramidal images, in contrast to QuPath that can pyramize the image if necessary.

**Comment by smistad** [comment]
Hello @andreped @cavenel and @vladpopovici 

Sorry for responding so slowly to this.

I have now found the reason for this error.
It was due to a rounding error of the pixel spacing in FAST.
After this fix, the segmentation renders at the correct location.

I will commit a fix to FAST soon, then we will need to rebuild FAST-Pathology with the new fix.
Stay tuned.

**Comment by smistad** [comment]
@cavenel I just tested the nuclei segmentation model on the data you sent @andreped with the fix, and it renders correctly now.

**Comment by cavenel** [comment]
I can confirm that it looks amazing now!
![image](https://github.com/AICAN-Research/FAST-Pathology/assets/6164758/a8a25cc7-457d-49a7-b94e-ba90d7ca44be)
