### ISSUE TITLE
Updating the import pyramidal tif script to the new folder structure

### ISSUE THREAD

**Issue by SahPet** [AICAN-Research/FAST-Pathology#46]
I think this script needs to be updated to work with the new folder structure for results from FastPathology: 

https://github.com/andreped/NoCodeSeg/blob/main/source/importPyramidalTIFF.groovy

The script assumes a different folder structure than what was before and also assumes the .tiff file has the same name as the image, whereas the newest update produces images named "segmentation.tiff".

**Comment by andreped** [comment]
Fixed in 9714fb170beeb28958d4d51cb6bb934bd4935635.

Could you test that the latest script works for you, @SahPet? Note that you will have issues if you run the script on a really large image, but lets just see it if works in a simple single/multiclass case first.

**Comment by andreped** [comment]
Note that for very small images, the result is stored in mhd/raw. This has been fixed in FP, but will not be made available until the next release. Will keep you updated, @SahPet.

**Comment by andreped** [comment]
@SahPet please, download the latest artifact for testing the latest version of FP:
Alternatively, you can download the latest binary pre-release by clicking this link: [Archive package (zip)](https://github.com/smistad/FAST/suites/7831098478/artifacts/331204004)

This version should be compatible with the recent changes in NoCodeSeg.

**Comment by andreped** [comment]
Alt dette skal ha blitt fikset nå, @SahPet. Erik fikset slik at alle segmenteringer lagres i TIFF-format, og jeg har oppdatert groovy-scriptet for å støtte det nye formatet i FP.

Last ned siste test-versjon her:
https://github.com/AICAN-Research/FAST-Pathology/actions/runs/3282310803

**Comment by andreped** [comment]
This fix is now part of the latest release:
https://github.com/AICAN-Research/FAST-Pathology/releases/tag/v1.1.0
