### ISSUE TITLE
Zoom is not following the pointer, but the middle of the screen

### ISSUE THREAD

**Issue by SahPet** [AICAN-Research/FAST-Pathology#47]
Two suggestions that would be a large improvement to user experience, in my opinion:

1) Zooming is not following the position of the arrow/pointer in the image (like Qupath and many other WSI renderers), but always follows the middle of the screen. This makes it hard to navigate the image. Any way to make the zoom center around the arrow instead? 

2) Also, there is now way to navigate the image with the keyboard arrow keys. Navigating a lot of WSIs with the mouse only is very demanding for the wrist and most pathologists use the keyboard arrows as well.

**Comment by andreped** [comment]
Suggestion (1) is something I have also wanted for a long time. Same with smoother movements including deaccelerations, similar to what QuPath (and OpenSeadragon used for LearnPathology) is doing.

**Comment by smistad** [comment]
Agreed. This can easily be added here: https://github.com/smistad/FAST/blob/master/source/FAST/Visualization/View.cpp#L702
However, the speed it should move towards the pointer might need to be optimized. 

Support for arrow keys is also quite easy to add, but which keys to use for zooming in and out?

**Comment by SahPet** [comment]
Sounds good:) One can always also add "+" and "-" as zoom keys, but I think most people just use mouse scroll together with the arrow keys. The hard part for the wrist is repeated "click-and-drag" movements, much more so than scrolling.

**Comment by smistad** [comment]
This has now been implemented in FAST and will appear in the next release. See commits https://github.com/smistad/FAST/commit/d4c3311edeb5d8682b56204651330fc6406c28f5 and https://github.com/smistad/FAST/commit/5c72bd86148e5ab0988fb07d3e7d16ab85194dae
