### ISSUE TITLE
macOS bug

### ISSUE THREAD

**Issue by andreped** [AICAN-Research/FAST-Pathology#50]
Just tried installing FP and testing it on a new macOS with Intel CPU, and for whatever reason it failed.

The machine did not have `homebrew` or anything like that. Hence, I set that up, but after following [this instruction](https://github.com/AICAN-Research/FAST-Pathology#macos-1013-or-newer) for installation. I got the following below:
```
dyld[68800]: Library not loaded: '/usr/local/opt/jpeg/lib/libjpeg.9.dylib'
Referenced from: '/Users/sigridberg/Downloads/fastpathology_macos10.13_1.0.1/lib/libFAST.4.4.0.dylib'
Reason: tried: '/usr/local/opt/jpeg/lib/libjpeg.9.dylib' (no such file), '/usr/local/lib/libjpeg.9.dylib' (no such file), '/usr/lib/libjpeg.9.dylib' (no such file)
```

If I tried to install `libjpeg` myself through `brew install libjpeg` FP launches, but when trying to load a simple WSI it fails and complains about mismatch in `libjpeg` version and what FP/FAST expects.

Have anyone observed the same?

**Comment by smistad** [comment]
Homebrew sometimes updates packages. Then you will get a mismatch between the library it was compiled with and the library downloaded by the user. Homebrew allows installing a specific version, but they don't seem to always keep previous versions lying around. The best fix for this is to bundle all libraries needed with the installer,

**Comment by andreped** [comment]
Aaah, that makes sense. Yeah, then the best solution would be to bundle all deps with the installer.

I have already made a separate issue on that: https://github.com/AICAN-Research/FAST-Pathology/issues/51

I can make an attempt on the installer later today or during the weekend.
