### ISSUE TITLE
cmake .. -D FAST_DIR=D:\FAST\cmake\ -G "Visual Studio 17 2022" -A x64

### ISSUE THREAD

**Issue by chaoyangxiao** [AICAN-Research/FAST-Pathology#56]
Hello, I'm having problems in the compilation process.

D:\FAST-Pathology\build>cmake .. -D FAST_DIR=D:\FAST\cmake\ -G "Visual Studio 17 2022" -A x64
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "FindFAST.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FAST", but
  CMake did not find one.

  Could not find a package configuration file provided by "FAST" with any of
  the following names:

    FASTConfig.cmake
    fast-config.cmake

  Add the installation prefix of "FAST" to CMAKE_PREFIX_PATH or set
  "FAST_DIR" to a directory containing one of the above files.  If "FAST"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "D:/FAST-Pathology/build/CMakeFiles/CMakeOutput.log".

How can I solve this problem? I look forward to your reply. Thank you.

**Comment by smistad** [comment]
Hm. Try removing the space after -D:
cmake .. -DFAST_DIR=D:\FAST\cmake\ -G "Visual Studio 17 2022" -A x64

And make sure the folder you specified for FAST_DIR actually exists

**Comment by chaoyangxiao** [comment]
> Hm. Try removing the space after -D: cmake .. -DFAST_DIR=D:\FAST\cmake\ -G "Visual Studio 17 2022" -A x64
> 
> And make sure the folder you specified for FAST_DIR actually exists

Thank you for your reply.
I compiled FAST first, and successfully displayed the information of FAST.
![M@~`N(Y8W48QTD2E{O_ED 5](https://user-images.githubusercontent.com/111733805/210914819-30d6e599-953b-4e2d-a06e-f160835d23b0.png)

Then use cmake ..-dfast _ dir = d: \ fast \ cmake \-g "Visual Studio 17 2022"-a x64 to compile FAST-pathology.
![9~8)QIM`2DCEUAY U}UH3ZY](https://user-images.githubusercontent.com/111733805/210914845-17d28ea8-5b99-4eda-b976-123b97627f6f.png)

But there are still problems. My FAST_DIR path here is the folder path after compiling FAST.
![~E~J}V({CPC~{Y9}D_J~P`C](https://user-images.githubusercontent.com/111733805/210914858-9641e35a-30d0-473d-8a89-9e44d1fa0179.png)

What does FAST_DIR specifically refer to?

**Comment by smistad** [comment]
Ah. You have to install fast after you build it. Setting CMAKE_INSTALL_PREFIX to where you want to install it and then and build the target install. You should then point it to the smaller folder inside this directory.

Note that you can also just download a precomputed version of fast as well.
