### ISSUE TITLE
cmake --build . --config Release --target fastpathology

### ISSUE THREAD

**Issue by chaoyangxiao** [AICAN-Research/FAST-Pathology#57]
Hello, thank you very much for sharing the code.
I got stuck in that build step when compile the fastpathology.
I have the following problems.
This bug has been bothering me for several days. I have encountered this problem in ubuntu and windows.

![0A}~7OTST0C)EIAT)A}SQGH](https://user-images.githubusercontent.com/111733805/211144085-42b783cc-b751-4555-ac4a-adb31db70c10.png)
“无法解析的外部符号“ means an external symbol that cannot be resolved in the picture.

Looking forward to your reply.

**Comment by smistad** [comment]
Hi, you have to enable HDF5 support when you build FAST. You do this by configuring cmake with -DFAST_MODULE_HDF5=ON and then recompile the install target again.

Note you can download a precompiled version of FAST instead at https://github.com/smistad/fast/releases these have all modules enabled.

**Comment by chaoyangxiao** [comment]
> Hi, you have to enable HDF5 support when you build FAST. You do this by configuring cmake with -DFAST_MODULE_HDF5=ON and then recompile the install target again.
> 
> Note you can download a precompiled version of FAST instead at https://github.com/smistad/fast/releases these have all modules enabled.

Thank you very much for your reply. You are very professional. Even though I am a novice, I have successfully compiled fast-pathology, and I can't wait to start using it.

Thank you again.
