### ISSUE TITLE
Failed to build CUDA engine for TensorRT

### ISSUE THREAD

**Issue by naguileraleal** [AICAN-Research/FAST-Pathology#63]
Hi there, I'm having a problem trying to make inference with a model downloaded from the hub. I was able to run the nuclei segmentation model, but then I installed TensorRT and can no longer make inference with any model. The error message is: Error parsing pipeline! Failed to build CUDA engine for TensorRT. I verified TensorRT installation as suggested in Nvidia installation guide and it seems to be working fine.

OS: Ubuntu 20.04
Relevant Libraries: cuDNN 8.8, TensorRT 8.5.3.1, CUDA 11.7
GPU: GeForce GTX 1660 Ti Mobile

Any help is much appreciated!

**Comment by smistad** [comment]
Hi

TensorRT works fine on my ubuntu 20 machine, however I have older libraries installed: tensorrt 8.4, cudnn 8.4, cuda 11.2.
Could maybe be a version issue, I can test upgrading and see what happens.
Are there any other error or warning messages besides "Failed to build CUDA engine for TensorRT"?

Note that you can manually specify which inference engine to use in your pipeline if you want to override the selection of TensorRT. You do this by setting `Attribute inference-engine OpenVINO` on the SegmentationNetwork process object in the pipeline file.

**Comment by naguileraleal** [comment]
Thanks for your quick response!
I set `Attribute inference-engine OpenVINO` and inference started working again.

I don't see a terminal window being launched when I launch FastPathology when I click the app's icon. I did not find a command to launch FastPathology from the terminal; could you tell me how to do that?

**Comment by smistad** [comment]
Open your terminal and go to /opt/fastpathology/bin/ and run the fastpathology executable in there:
```bash
cd /opt/fastpathology/bin/
./fastpathology
```

Then you should get any warnings and errors in this terminal.

**Comment by naguileraleal** [comment]
Today I tried running fastpathology from the terminal and making inference with the previously mentioned model using TensorRT, and it works correctly now.
I did not make any changes to the libraries I'm using.

I'm sorry but I can't explain this behaviour. I'll close this issue now. Thanks for your help!

**Comment by andreped** [comment]
Might be that you needed to restart your machine after installing CUDA and what not. This should atleast be needed after installing drivers. Anyways. Glad its working for you!
