### ISSUE TITLE
Opening segmentation output

### ISSUE THREAD

**Issue by naguileraleal** [AICAN-Research/FAST-Pathology#64]
Hello!
I'm having trouble opening the output (tiff mask) generated by the "Epithelium segmentation in colonic mucosa (H&E Stained)" model provided by FastPathology (I'm running version v1.1.0). This model was run on an H&E WSI, and the segmentation is correctly displayed in FastPathology. 
The problem arises when I try to open the output using QuPath (or any other WSI viewer; I've tried QuPath 0.3.2, PMA.start, ASAP 2.1).
QuPath offers me the "Auto pyramidalize" option. When I select "Yes" the image is just black pixels. When I select "No" QuPath crashes since it runs out of memory.

A previous error message from QuPath used to tell me that I needed to convert this output to a pyramidal TIFF, and I followed this tutorial http://www.andrewjanowczyk.com/converting-an-existing-image-into-an-openslide-compatible-format/. I had no success with it though, since the VIPS and the ImageMagick command both throw errors and do not complete the conversion.

This is the ImageMagick output when following the first step of the tutorial
```
convert "Segmentation.tiff" -define tiff:tile-geometry=256x256 -compress jpeg 'ptif:pyramidal.tiff'
convert-im6.q16: width or height exceeds limit `segmentation.tiff' @ error/cache.c/OpenPixelCache/3911.
convert-im6.q16: no images defined `ptif:pyramidal.tiff' @ error/convert.c/ConvertImageCommand/3258.
```
This is the VIPS output when following the first step of the tutorial
```
vips tiffsave Segmentation.tiff" "/home/sofia/fastpathology/projects/Nucleos/results/44-D5/Nuclei segmentation/Segmentation/pyramidal.tiff" --tile --pyramid --compression=jpeg --Q=85

(vips:41942): VIPS-WARNING **: 20:57:36.193: error in tile 192 x 0
(vips:41942): VIPS-WARNING **: 20:57:36.193: error in tile 384 x 0
(vips:41942): VIPS-WARNING **: 20:57:36.193: error in tile 576 x 0
(vips:41942): VIPS-WARNING **: 20:57:36.193: error in tile 768 x 0
(vips:41942): VIPS-WARNING **: 20:57:36.193: error in tile 960 x 0

\<more lines like those\>

TIFFFillTile: 0: Invalid tile byte count, tile 195
TIFFFillTile: 0: Invalid tile byte count, tile 196
TIFFFillTile: 0: Invalid tile byte count, tile 197
TIFFFillTile: 0: Invalid tile byte count, tile 198
TIFFFillTile: 0: Invalid tile byte count, tile 199
TIFFFillTile: 0: Invalid tile byte count, tile 200
TIFFFillTile: 0: Invalid tile byte count, tile 201
TIFFFillTile: 0: Invalid tile byte count, tile 202
```

I've tried this process on both Windows 11 and Ubuntu 20.04

Any help is much appreciated. Thanks in advance!

**Comment by naguileraleal** [comment]
Thanks for your quick response!

I was hoping that I could open the segmentation.tiff file as any other WSI, since I wanted to tile it and import it as masks in QuickAnnotator. Guess I won't be able to achieve that.

I knew that script from the NoCodeSeg project. I have already run it succesfully on other WSIs, although the generation of the .xml annotation file takes several hours (tested on Nuclei Segmentation, size of the WSI reported by QuPath: 86000x107000 pixels).

I tried running the script on the new segmentation anyways. The Groovy script produced this output:

```
ERROR: NullPointerException at line 101: Cannot invoke method getROI() on null object

ERROR: org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
    org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
    org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
    org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
    Script18.run(Script18.groovy:102)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:982)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:914)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:829)
    qupath.lib.gui.scripting.DefaultScriptEditor$ProjectTask.call(DefaultScriptEditor.java:1502)
    qupath.lib.gui.scripting.DefaultScriptEditor$ProjectTask.call(DefaultScriptEditor.java:1449)
    javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
    java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    java.base/java.lang.Thread.run(Unknown Source)
```

I tried various values of the parameters "downsample" (0, 1, 2, 10) and "level" (0, 1) of the script, without success. I'll include the values of the parameters now.

```
// --- SET THESE PARAMETERS ---
def masksPath = 'C:\\Users\\nicol\\fastpathology\\projects\\glandulas\\results'  // path to where TIFFs are stored (FastPathology project)
def downsample = 0                      // which scaling factor to use, if the segmentation is produced at a lower magnification level
def level = 0                           // which level to extract segmentation from (choosing 0 may be slow)
def extension = ".tiff"                 // pyramidal TIFF
def classNames = ["Background", "Epithelium"]   // names of classes of interest (in this case two classes + background)
def taskName = "Epithelium segmentation in colonic mucosa (HE-Stained)"    // name of task, which correspond to which task that was run in FastPathology to get this result
int channel = 0                         // 0-based index for the channel to threshold
def fromFP = true                       // whether result is from FastPathology or not, if no, we assume that the TIFF lie directly in the maskPath directory with the same name.
// ----------------------------
```

This is the pipeline.fpl that generated the segmentation

```
PipelineName "Epithelium segmentation in colonic mucosa (HE-stained)"

PipelineDescription "Segmentation of epithelial cells in HE-stained biopsies of colonic mucosa of active and inactivate inflammatory bowel disease. For more info see the article 'Code-Free Development and Deployment of Deep Segmentation Models for Digital Pathology' Frontiers in Medicine 2022 https://www.frontiersin.org/articles/10.3389/fmed.2021.816281/full and also the webpage https://github.com/andreped/NoCodeSeg."

PipelineInputData WSI "Whole-slide image"

PipelineOutputData segmentation stitcher 0

Attribute classes "Background;Epithelium"



### Processing chain

ProcessObject tissueSeg TissueSegmentation

Attribute threshold 70

Input 0 WSI



ProcessObject patch PatchGenerator

Attribute patch-size 512 512

Attribute patch-magnification 10

Attribute patch-overlap 0.05

Attribute mask-threshold 0.02

Input 0 WSI

Input 1 tissueSeg 0



ProcessObject network SegmentationNetwork

Attribute scale-factor 1.0

Attribute model "$CURRENT_PATH$/../colon-epithelium-segmentation-he-model/HE_IBDColEpi_512_2class_140222.onnx"

Input 0 patch 0



ProcessObject stitcher PatchStitcher

Input 0 network 0



### Renderers

Renderer imgRenderer ImagePyramidRenderer

Input 0 WSI



Renderer segRenderer SegmentationRenderer

Attribute opacity 0.5

Attribute border-opacity 1.0

Input 0 stitcher 0
```

Here's the link to the segmentation generated https://drive.google.com/file/d/1-7b6XHk4aPnzyVKxTTqKwa4oVKVXQ3TO/view?usp=share_link (couldn't upload it to github). I'll ask for permission for uploading the WSI associated with the segmentation, and I'll share it with you if I can.

**Comment by andreped** [comment]
Try removing "Background" in the class names of the gropvy script. There is only one class of interest. Hence, there should only be one string in the list, i.e., Epithelium.

I see now that the comment I made was confusing. I will correct that. Cheers!

**Comment by andreped** [comment]
> I was hoping that I could open the segmentation.tiff file as any other WSI, since I wanted to tile it and import it as masks in QuickAnnotator. Guess I won't be able to achieve that.

Oh, but yes you can. The reason why the image is all "black" is just because the pyramidal TIFF annotation image is stored with uints 0 and 1 (if you are doing binary segmentation). As the intensity range is generally in [0, 255], the uint 1 value is interpreted as almost black, and hence, it is challenging to see any differences between annotations and background.

There are actual pixels there, you just cannot easily see them. If you perform simple thresholding (see [here](https://qupath.readthedocs.io/en/0.3/docs/tutorials/thresholding.html)), you should be able to see the annotations (set threshold to 0 or 1).

**Comment by naguileraleal** [comment]
Hi! Sorry for the delay.

> Try removing "Background" in the class names of the gropvy script. There is only one class of interest. Hence, there should only be one string in the list, i.e., Epithelium.

After removing the "Background" class from the list, the script ran correctly, and I was able to import the annotations to QuPath in XML format. 


> As a sanity check, to view the annotations, you could perform simple thresholding in QuPath (see [here](https://qupath.readthedocs.io/en/0.3/docs/tutorials/thresholding.html)). Try setting the threshold to 0 or 1.

Your suggestions for correctly visualizing the output segmentation from FastPath in QuPath worked beautifully. I was then able to cut the thresholded .tiff into tiles. Thanks! I was only able to only do this for the output of the "Epithelium segmentation in colonic mucosa (H&E Stained)" model, though. When trying with the output of the "Nuclei Segmentation" model, I was not able to load the `segmentation.tiff` output into QuPath. The error message is "Added images (1/1) - image null" and then the image never appears in the list of images of the QuPath project. This file is considerably larger than the previous one (300MB vs 7MB).

**Comment by andreped** [comment]
My thresholding "trick" was only relevant to check that there were annotations in the image and not just black.

After importing, you could try to export the image as tiles. However, might be that you need to convert the image to proper annotations first, for instance by thresholding to generate annotation objects.

**Comment by naguileraleal** [comment]
Running the script on this project results in the following error

`WARN: Unable to open file:/C:/Users/nicol/fastpathology/projects/nucleos/results/44-D5/Nuclei%20segmentation/Segmentation/Segmentation.tiff with OpenSlide: TIFFRGBAImageGet failed`

Memory values are normal (~7GB out of 15GB).

Anyways, the output of this script is not so relevant to my project as it is being able to load the .tiff file in QuPath. 

[Here](https://drive.google.com/file/d/1acV340f62siqHcI7Y-7ag-3D5po5n1Kc/view?usp=share_link) is the WSI over which I ran the Nuclei Segmentation model in FastPath. This in turn generated the Segmentation.tiff file which I'm now trying to import into QuPath (without success). I'll leave it here just in case you want to give it a try.

**Comment by andreped** [comment]
@naguileraleal Did you manage to resolve this issue?

**Comment by naguileraleal** [comment]
Sorry for not closing this issue. I've not tried the groovy script again since all I needed was to import the .tiff segmentation in QuPath as an image. I did not need to generate QuPath annotation objects.
My original issue was solved

**Comment by andreped** [comment]
> Sorry for not closing this issue before.

No worries! :] Feel free to open a new issue or discussion, if you are experiencing any others issues/obstacles. We have more time dedicated this fall to fix issues and improve FP.
