### ISSUE TITLE
Exported Pyramidal TIFF shifted in QuPath

### ISSUE THREAD

**Issue by cavenel** [AICAN-Research/FAST-Pathology#76]
Hi,

When exporting a segmentation from FastPathology to QuPath using the groovy script from https://github.com/andreped/NoCodeSeg/blob/main/source/importPyramidalTIFF.groovy, I get a huge shift:
![image](https://github.com/AICAN-Research/FAST-Pathology/assets/6164758/48e23d01-eb1c-436d-aafa-343091539919)

I believe this is because my images have a bounding box around the tissue, as seen in openslide:
```
openslide.bounds-height: '39324'
openslide.bounds-width: '31246'
openslide.bounds-x: '32752'
openslide.bounds-y: '109084'
openslide.level-count: '11'
openslide.level[0].downsample: '1'
openslide.level[0].height: '206613'
openslide.level[0].width: '91287'
```
QuPath only opens this bounding box (of size 31246x39324) while the generated TIFF from FastPathology is covering the whole image (91287x206613, downscaled 4 times) and doesn't preserve the bounding box info:

![FastPathologyQuPath](https://github.com/AICAN-Research/FAST-Pathology/assets/6164758/7a284ef0-67a3-40c7-b3f4-55fbda738aba)

I am working on a workarund on the QuPath side (by shifting the annotations by (-bounds.x, -bounds.y) but it would be nice to add the bounds also in the exported TIFF from FastPathology.

**Comment by andreped** [comment]
Which magnification level did you run the model at? See the FPL file. From what you say above, the image is downsampled 4 times. Have you remember to update this value from 2 -> 4:
https://github.com/andreped/NoCodeSeg/blob/main/source/importPyramidalTIFF.groovy#L23

**Comment by cavenel** [comment]
Yes, the screenshot is taken with the wrong downsample indeed, sorry. Here is with correct downsample of 4:
![image](https://github.com/AICAN-Research/FAST-Pathology/assets/6164758/4eeb9bbe-7912-4819-914f-f1bcfcf0f072)

For the shift, I have two workarounds working in QuPath now (thanks to https://forum.image.sc/t/level-dimensions-in-qupath-image-and-original-slide-image-differ/78842/3):
 - open the image without the bounds (provide `--no-crop` as an optional argument – but that will cause lots of empty padding to be added.)
 - or shift annotations after downscale:
 ```
 def imageServer = getCurrentServer();
def shiftX = -imageServer.boundsX;
def shiftY = -imageServer.boundsY;
[...]
    def oldObjects = getAnnotationObjects().findAll{it.getPathClass() == getPathClass(currClassName)}
    def transform = java.awt.geom.AffineTransform.getTranslateInstance(shiftX, shiftY)
    transform.concatenate(java.awt.geom.AffineTransform.getScaleInstance(downsample, downsample))
    def newObjects = oldObjects.collect {p -> PathObjectTools.transformObject(p, transform, false)}
 ```
